### ISSUE TITLE
Do you have any interest in another maintainer for bp-album?

### ISSUE THREAD

**Issue by OllieJones** [BP-Media/bp-album#11]
Hello.
If you were willing I would bring bp-album up to date. It's good stuff, and a refresh would make it even better.

You would need to add me as a contributor (or even owner) from https://wordpress.org/plugins/bp-album/advanced/.  I can do the work from a fork of this repo, or you could add me as a contributor here.

**Comment by modemlooper** [comment]
You can support this plugin through pull requests. Thanks!

**Comment by OllieJones** [comment]
Perfect!
